### ISSUE TITLE
Search movies by names

### ISSUE THREAD

**Issue by vceci** [vceci/python-exercise-vceci#5]
**User Story**

As a person that has access to the movies file, I want to be able to search for movies using their name. I want to add a new option to the menu, 'sn', which prompts the user to enter any word, and then displays a list of movies that have that word in its name. This function should be case insensitive so that it is extremely user friendly

* persona: person who wants to search for movies by their name in the movie file
* feature: a menu option that prompts the user to enter a word, and then displays a list of movie names that contain that word (case insensitive)
* business value: this program will allow users to easily search for a movie that they are looking for with limited information; the case insensitivity allows for more leeway with the capability of the word the user provides

**Task List**
- [x] create a menu option 'sn' to initiate the program
- [x] program that prompts the user to provide a word to use in the search
- [x] generates a list of movie names that contain that word, with case insensitivity

**Acceptance Criteria**
1. only lists movies that have the word the user provides in its name
2. prompts the user to provide a word after entering 'sn'
3. the list only provides movie names and not their cast
4. the list is generated with case insensitivity

**Acceptance Tests**
1. after entering 'sn' at the menu, the program prompts the user to provide a word
2. the program generates a list of movie names that contain that word with case insensitivity
