### ISSUE TITLE
Search movies by cast

### ISSUE THREAD

**Issue by vceci** [vceci/python-exercise-vceci#7]
**User Story**

As a person that has access to the movies file, I want to be able to search for movies using their cast. I want to add a new option to the menu, 'sc', which prompts the user to enter any word, and then displays a list of movies that have that word in their cast. This function should be case insensitive so that it is extremely user friendly.

* persona: person who wants to search for movies by their cast in the movie file
* feature: a menu option that prompts the user to enter a word, and then displays a list of movies that contain that word in their cast (case insensitive)
* business value: this program will allow users to easily search for a movie that they are looking for with limited information; the case insensitivity allows for more leeway with the capability of the word the user provides

**Task List**
- [x] create a menu option 'sc' to initiate the program
- [x] program that prompts the user to provide a word to use in the search
- [x] generates a list of movie names that contain that word in the cast, with case insensitivity

**Acceptance Criteria**
1. only lists movies that have the word the user provides in its cast
2. prompts the user to provide a word after entering 'sc'
3. the list provides the name of the movie and the cast members that have that word in their name
4. the list is generated with case insensitivity

**Acceptance Tests**
1. after entering 'sc' at the menu, the program prompts the user to provide a word
2. the program generates a list of movie names and cast members that contain that word in their cast, with case insensitivity
